# source: https://neovide.dev/config-file.html

# backtraces_path = "/path/to/neovide_backtraces.log" # see below for the default platform specific location
fork = false
frame = "none"              # "full"
idle = true
maximized = false
mouse-cursor-icon = "arrow"
# neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false

[font]
normal = [
  "MesloLGS Nerd Font Mono",
] # Will use the bundled Fira Code Nerd Font by default
size = 20.0
