tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"

brew "stow"
cask "karabiner-elements"
brew "yqrashawn/goku/goku"

# tap "homebrew/bundle"
# tap "homebrew/services"
# tap "qmk/qmk"
# tap "teamookla/speedtest"
# tap "yqrashawn/goku"
# 
# brew "fzf"
# brew "yqrashawn/goku/goku"
#  
# cask "alfred"
# cask "figma"
# cask "hammerspoon"
# cask "iterm2"
# cask "karabiner-elements"
# cask "sublime-text"
# cask "transmission"
# cask "vlc"
