-- Example app generated by Claude Sonner 4
-- Use as a template to develop your own Hammerspoon menubar app
-- Create a new menubar item
local menubar = hs.menubar.new()

-- Set the title or icon for the menubar item
menubar:setTitle("MyApp")

-- Define the menu structure
local menuTable = {
	{
		title = "Action 1",
		fn = function()
			hs.alert.show("Action 1 executed")
		end,
	},
	{
		title = "Action 2",
		fn = function()
			hs.alert.show("Action 2 executed")
		end,
	},
	{
		title = "-", -- This creates a separator line
	},
	{
		title = "About",
		fn = function()
			hs.alert.show("MyApp v1.0\nCreated with Hammerspoon")
		end,
	},
	{
		title = "Quit",
		fn = function()
			menubar:delete()
			menubar = nil
		end,
	},
}

-- Set the menu
menubar:setMenu(menuTable)
