[[entry]]
favorited_at = "2026-09-11T07:07:40Z"
path = "https://radio.cliamp.stream/ncs-dnb/stream"
title = "NCS Drum & Bass"
realtime = true

[[entry]]
favorited_at = "2026-09-10T17:30:41Z"
path = "https://radio.cliamp.stream/lofi/stream"
title = "Lofi"
realtime = true
